language: ruby
rvm:
- 2.4.1
sudo: required

services:
  - mysql
  - docker
  - memcached
  - redis-server

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

before_install:
  - mysql -e 'CREATE DATABASE lupo_test;'

install:
  - travis_retry bundle install

before_script:
  - memcached -p 11211 &
  - cp .env.travis .env
  - mkdir -p tmp/pids
  - mkdir -p log
  - bundle exec sidekiq -d -e production --config config/sidekiq.yml -L log/sidekiq.log
  - bundle exec rake db:setup RAILS_ENV=test

script:
  - bundle exec rspec spec
  - bundle exec codeclimate-test-reporter

after_success:
  - if [ "$TRAVIS_BRANCH" == "no-solr" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
    export REPO=datacite/lupo;
    docker build -f Dockerfile -t $REPO:$COMMIT .;
    docker push datacite/lupo:no-solr;
    fi

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
