concurrency: 15
delay: 0
pidfile: tmp/pids/shoryuken.pid
queues:
  - lupo

groups:
  import:
    concurrency: 10
    queues:
      - lupo_import
  transfer:
    concurrency: 10
    queues:
      - lupo_transfer
  background:
    concurrency: 3
    queues:
      - lupo_background
