concurrency: 10
delay: 0
pidfile: tmp/pids/shoryuken.pid
queues:
  - lupo

groups:
  transfer:
    concurrency: 3
    queues:
      - lupo_transfer
  background:
    concurrency: 3
    queues:
      - lupo_background
