name: Build
on:
  push:
    branches:
      - "master"
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      COMPOSE_INTERACTIVE_NO_CLI: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: ${{ GITHUB_REPOSITORY }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Lint and Test
        run: |
          cp .env.build .env
          docker-compose up -d
          docker-compose exec -T web bundle exec rubocop -a
          docker-compose exec -T web bundle exec rake db:setup RAILS_ENV=test
          docker-compose exec -T web bundle exec rspec
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
        run: docker push datacite/lupo
