name: Deploy
on:
  push:
    branches:
      - "master"
env:
  IMAGE_TAG: main
jobs:
  lint:
    uses: ./.github/workflows/rubocop.yml
  test:
    uses: ./.github/workflows/parallel_ci.yml
    secrets: inherit
  call_build_and_push:
    needs: test
    uses: ./.github/workflows/build.yml
    with:
      image_name: ${{ github.repository }}
      image_tag: ${{ env.IMAGE_TAG }}
    secrets: inherit
  deploy:
    needs: [test, call_build_and_push]
    runs-on: ubuntu-latest
    #env:
      #BRANCH: ${{ github.ref_name }}
      #SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout terraform config repo
        uses: actions/checkout@v3
        with:
          # public repo with terraform configuration
          repository: 'datacite/mastino'
          persist-credentials: false
      - name: Commit changes to terraform config repository
        # use go template in terraform config repository to update git sha and tag
        # commit and push changes to trigger terraform workflow
        run: |
          export GIT_SHA=${{ github.sha }}
          export GIT_TAG=${{ env.IMAGE_TAG }}
          wget https://github.com/jwilder/dockerize/releases/download/v0.6.0/dockerize-linux-amd64-v0.6.0.tar.gz
          tar -xzvf dockerize-linux-amd64-v0.6.0.tar.gz
          rm dockerize-linux-amd64-v0.6.0.tar.gz
          ./dockerize -template stage/services/client-api/_lupo.auto.tfvars.tmpl:stage/services/client-api/_lupo.auto.tfvars

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add stage/services/client-api/_lupo.auto.tfvars
          git commit -m "Adding lupo git variables for commit ${{ github.sha }}"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: 'datacite/mastino'
          branch: 'refs/heads/master'
          tags: false
