name: Test Pull Request
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  lint:
    uses: ./.github/workflows/rubocop.yml
  parallel-test:
    uses: ./.github/workflows/parallel_ci.yml
    secrets: inherit
