name: Release
on:
  release:
    types: [published]
env:
  IMAGE_TAG: ${{ github.ref_name }}
jobs:
  lint:
    uses: ./.github/workflows/rubocop.yml
  test:
    uses: ./.github/workflows/parallel_ci.yml
    secrets: inherit
  build:
    needs: test
  call_build_and_push:
    needs: test
    uses: ./.github/workflows/build.yml
    with:
      image_name: ${{ github.repository }}
      image_tag: ${{ env.IMAGE_TAG }}
    secrets: inherit

  deploy:
    needs: [test, call_build_and_push]
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout terraform config repo
        uses: actions/checkout@v3
        with:
          # public repo with terraform configuration
          repository: 'datacite/mastino'
          persist-credentials: false
      - name: Commit changes to terraform config repository
        # use go template in terraform config repository to update git sha and tag
        # commit and push changes to trigger terraform workflow
        run: |
          export GIT_SHA=${{ github.sha }}
          export GIT_TAG=${{ env.IMAGE_TAG }}
          wget https://github.com/jwilder/dockerize/releases/download/v0.6.0/dockerize-linux-amd64-v0.6.0.tar.gz
          tar -xzvf dockerize-linux-amd64-v0.6.0.tar.gz
          rm dockerize-linux-amd64-v0.6.0.tar.gz

          ./dockerize -template prod-eu-west/services/client-api/_lupo.auto.tfvars.tmpl:prod-eu-west/services/client-api/_lupo.auto.tfvars
          ./dockerize -template test/services/client-api/_lupo.auto.tfvars.tmpl:test/services/client-api/_lupo.auto.tfvars

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add prod-eu-west/services/client-api/_lupo.auto.tfvars
          git add test/services/client-api/_lupo.auto.tfvars
          git commit -m "Adding lupo git variables for tag ${{ env.IMAGE_TAG }}"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: 'datacite/mastino'
          branch: 'refs/heads/master'
          tags: false

      - name: Notify Slack
        uses: edge/simple-slack-notify@master
        with:
          channel: '#ops'
          color: 'good'
          text: 'Version <https://github.com/${{ github.repository }}/${{github.ref}}> of the <https://api.datacite.org|REST API> is being released to test and production.'
          failure_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) build failed'
          fields: |
            [{ "title": "Committed by", "value": "<https://github.com/${{ github.repository }}/commits?author=${{ github.actor }}|${{ github.actor }}>", "short": true },
             { "title": "Commit SHA", "value": "<https://github.com/${{ github.repository }}/commit/${{ steps.extract_variables.outputs.GIT_SHA }}|${{ steps.extract_variables.outputs.GIT_SHA_SHORT }}>", "short": true },
             { "title": "Repository", "value": "<https://github.com/${{ github.repository }}|${{ github.repository }}>", "short": true },
             { "title": "Release", "value": "<https://github.com/${{ github.repository }}/releases/tag/${{ steps.extract_variables.outputs.TAG }}|${{ steps.extract_variables.outputs.TAG }}>", "short": true }]
